import { UauInsumo, UauObra } from "./types";

export const FIXTURE_OBRAS: UauObra[] = [
  {
    codigo: "9998",
    empresa: 9999,
    nome: "OBRA X",
    tipo: 1,
    tipoLabel: "Horizontal",
    dataInicio: "2016-03-01T00:00:00",
    dataFim: "2020-12-31T00:00:00",
    dataAlteracao: "2025-06-12T00:00:00",
    status: 0,
  },
  {
    codigo: "9999",
    empresa: 9999,
    nome: "OBRA TESTE",
    tipo: 2,
    tipoLabel: "Vertical",
    dataInicio: "2015-01-01T00:00:00",
    dataFim: "2050-12-31T00:00:00",
    dataAlteracao: "2025-09-11T00:00:00",
    status: 0,
  },
];

export const FIXTURE_INSUMOS: Record<string, UauInsumo[]> = {
  "9999": [
    {
      codigo: "aco0012",
      descricao: "ARAME RECOZIDO BWG 18 FIO 1,24MM (PG7) NBR 5589",
      categoria: "aco",
      categoriaDescricao: "Aço",
      unidade: "kg",
      especificacao: "",
      orcamento: 1,
    },
    {
      codigo: "sem0241",
      descricao: "ARMAÇÃO (CORTE, DOBRA E MONTAGEM DE AÇO)",
      categoria: "sem",
      categoriaDescricao: "Sub Empreiteiros",
      unidade: "Kg",
      especificacao: "",
      orcamento: 1,
    },
    {
      codigo: "con0005",
      descricao: "Concreto Fck25 Mpa Usinado Bombeado Brita 1",
      categoria: "con",
      categoriaDescricao: "Concreto",
      unidade: "m3",
      especificacao: "",
      orcamento: 1,
    },
    {
      codigo: "pro0004",
      descricao: "Projeto Arquitetônico",
      categoria: "pro",
      categoriaDescricao: "Projeto",
      unidade: "vb",
      especificacao: "",
      orcamento: 1,
    },
    {
      codigo: "pro0023",
      descricao: "Projeto de Paisagismo",
      categoria: "pro",
      categoriaDescricao: "Projeto",
      unidade: "vb",
      especificacao: "",
      orcamento: 1,
    },
    {
      codigo: "pro0029",
      descricao: "Projeto Estrutural",
      categoria: "pro",
      categoriaDescricao: "Projeto",
      unidade: "vb",
      especificacao: "",
      orcamento: 1,
    },
    {
      codigo: "pro0057",
      descricao: "Projeto de Fundação",
      categoria: "pro",
      categoriaDescricao: "Projeto",
      unidade: "vb",
      especificacao: "",
      orcamento: 1,
    },
    {
      codigo: "pro0065",
      descricao: "Projeto Fachada",
      categoria: "pro",
      categoriaDescricao: "Projeto",
      unidade: "vb",
      especificacao: "",
      orcamento: 1,
    },
    {
      codigo: "pro0066",
      descricao: "Projeto Incêndio",
      categoria: "pro",
      categoriaDescricao: "Projeto",
      unidade: "vb",
      especificacao: "",
      orcamento: 1,
    },
    {
      codigo: "pro0067",
      descricao: "Projetos Compatibilização",
      categoria: "plf",
      categoriaDescricao: "Planejamento - Mao de Obra",
      unidade: "vb",
      especificacao: "",
      orcamento: 1,
    },
    {
      codigo: "rhu0018",
      descricao: "PPRA",
      categoria: "rhu",
      categoriaDescricao: "Recursos Humanos",
      unidade: "vb",
      especificacao: "",
      orcamento: 1,
    },
    {
      codigo: "rhu0023",
      descricao: "PCMSO",
      categoria: "rhu",
      categoriaDescricao: "Recursos Humanos",
      unidade: "vb",
      especificacao: "",
      orcamento: 1,
    },
  ],
  "9998": [
    {
      codigo: "aco0080",
      descricao: "TELA DE AÇO CA60 NERVURADA SOLDADA Q283",
      categoria: "aco",
      categoriaDescricao: "Aço",
      unidade: "vb",
      especificacao: "",
      orcamento: 1,
    },
    {
      codigo: "pro0004",
      descricao: "Projeto Arquitetônico",
      categoria: "pro",
      categoriaDescricao: "Projeto",
      unidade: "vb",
      especificacao: "",
      orcamento: 1,
    },
  ],
};
